import { motion } from "motion/react";
import { Music2, MessageCircle, AtSign, Play, Camera, ArrowDown, ArrowUpRight } from "lucide-react";

const reveal={initial:{opacity:0,y:24},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.2},transition:{duration:.75,ease:"easeOut" as const}};
const capabilities=[
  ["01","市场与用户机会判断","从市场变化、用户任务与业务目标中识别值得解决的问题。"],
  ["02","AI产品规划与落地","把模糊机会拆解为清晰的产品目标、功能边界和验证路径。"],
  ["03","前沿技术产品化评估","判断模型能力、可靠性与成本，找到可执行的产品切口。"]
];
const socials=[["Music",Music2],["Facebook",MessageCircle],["Twitter",AtSign],["YouTube",Play],["Instagram",Camera]] as const;

function Logo(){return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M 4.688 136 C 68.373 136 120 187.627 120 251.312 C 120 252.883 119.967 254.445 119.905 256 L 0 256 L 0 136.096 C 1.555 136.034 3.117 136 4.688 136 Z M 251.312 136 C 252.883 136 254.445 136.034 256 136.096 L 256 256 L 136.095 256 C 136.032 254.438 136.001 252.875 136 251.312 C 136 187.627 187.627 136 251.312 136 Z M 119.905 0 C 119.967 1.555 120 3.117 120 4.688 C 120 68.373 68.373 120 4.687 120 C 3.117 120 1.555 119.967 0 119.905 L 0 0 Z M 256 119.905 C 254.445 119.967 252.883 120 251.312 120 C 187.627 120 136 68.373 136 4.687 C 136 3.117 136.033 1.555 136.095 0 L 256 0 Z"/></svg>}

export default function App(){return <main className="relative w-full min-h-[115vh] overflow-x-hidden flex flex-col items-center font-sans selection:bg-white/20 selection:text-white text-white">
  <video className="fixed inset-0 w-full h-full object-cover z-[0]" src="https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260429_114316_1c7889ad-2885-410e-b493-98119fee0ddb.mp4" autoPlay loop muted playsInline/><div className="fixed inset-0 z-[1] video-shade pointer-events-none"/>
  <nav className="fixed top-0 inset-x-0 z-30 border-b border-white/10 bg-black/10 backdrop-blur-sm"><div className="max-w-7xl mx-auto px-5 md:px-8 h-20 flex items-center justify-between"><a href="#home" className="flex items-center gap-3"><Logo/><span className="text-lg font-medium">陈思东</span></a><div className="flex items-center gap-5 md:gap-8 text-xs text-white/70"><a href="#about" className="hidden sm:block hover:text-white">关于我</a><a href="#capabilities" className="hidden sm:block hover:text-white">核心能力</a><a href="#contact" className="rounded-full border border-white/30 px-4 py-2.5 hover:bg-white hover:text-black transition-colors">联系我</a></div></div></nav>
  <div className="relative z-10 w-full max-w-7xl px-5 md:px-8 flex flex-col grow">
    <section id="home" className="min-h-screen flex items-end pb-16 md:pb-24 pt-32"><motion.div {...reveal} className="w-full grid md:grid-cols-12 gap-10 items-end"><div className="md:col-span-9"><p className="text-[11px] uppercase tracking-[.26em] text-white/60 mb-6">AI Product Manager · Market · Product</p><h1 className="text-[20vw] sm:text-[15vw] md:text-[10.5rem] leading-[.82] tracking-[-.07em] font-medium">陈思东</h1><h2 className="mt-8 text-3xl sm:text-4xl md:text-6xl leading-tight tracking-[-.04em]">懂市场落地的<br/><span className="text-white/60">前沿AI产品经理</span></h2></div><div className="md:col-span-3 md:pb-2"><p className="text-sm leading-7 text-white/70">将前沿AI能力、用户需求与商业机会连接起来，推动真正可用的产品落地。</p><a href="#about" className="mt-8 inline-flex items-center gap-3 text-xs uppercase tracking-wider">继续了解 <ArrowDown size={15}/></a></div></motion.div></section>
    <section id="about" className="min-h-[85vh] py-28 md:py-44 flex items-center"><motion.div {...reveal} className="grid md:grid-cols-12 gap-10 md:gap-16 w-full border-t border-white/20 pt-10"><div className="md:col-span-4"><p className="text-[11px] uppercase tracking-[.24em] text-white/60">About / 关于我</p></div><div className="md:col-span-8"><h2 className="text-4xl md:text-7xl leading-[1.12] tracking-[-.04em]">不只理解技术，<br/>更理解市场。</h2><p className="mt-10 max-w-2xl text-base md:text-lg leading-8 text-white/70">我是陈思东，一名关注市场机会与产品落地的AI产品经理。我持续研究前沿技术如何进入真实场景，并转化为用户愿意使用、组织能够持续经营的产品。</p></div></motion.div></section>
    <section id="capabilities" className="py-28 md:py-44"><motion.div {...reveal}><p className="text-[11px] uppercase tracking-[.24em] text-white/60">Capabilities / 核心能力</p><h2 className="mt-6 text-4xl md:text-7xl leading-tight tracking-[-.04em]">把复杂问题，<br/>变成产品路径。</h2><div className="grid md:grid-cols-3 mt-16 border-t border-white/20">{capabilities.map(([n,title,text],i)=><article key={n} className={`min-h-80 py-8 md:px-8 flex flex-col ${i?"md:border-l border-white/20":""}`}><span className="text-[10px] tracking-widest text-white/50">{n}</span><h3 className="mt-auto text-2xl leading-snug">{title}</h3><p className="mt-5 text-sm leading-7 text-white/60">{text}</p></article>)}</div></motion.div></section>
    <div className="mt-auto pt-24 md:pt-44" id="contact"><motion.div {...reveal} className="mb-14 md:mb-20 flex flex-col md:flex-row gap-8 justify-between items-start md:items-end"><div><p className="text-[11px] uppercase tracking-[.24em] text-white/60 mb-5">Start a conversation</p><h2 className="text-4xl md:text-7xl tracking-[-.04em]">聊聊AI产品机会。</h2></div><a href="#wechat" className="inline-flex gap-3 items-center rounded-full bg-white text-black px-6 py-3.5 text-sm">加微信聊聊 <ArrowUpRight size={16}/></a></motion.div>
      <motion.footer initial={{opacity:0,y:40}} animate={{opacity:1,y:0}} transition={{duration:1,delay:.4,ease:"easeOut"}} className="liquid-glass w-full rounded-3xl p-6 md:p-10 text-white/70 mt-32 md:mt-64"><div className="grid grid-cols-1 md:grid-cols-12 gap-10 md:gap-12 mb-10"><div className="md:col-span-5"><div className="flex items-center gap-3 text-white"><Logo/><span className="text-xl font-medium">陈思东</span></div><p className="text-sm leading-relaxed max-w-sm mt-5">关注AI前沿，也关心技术如何进入真实市场、解决真实问题。如果你正在寻找AI产品人才或合作伙伴，欢迎联系我。</p></div><div className="md:col-span-7 grid grid-cols-2 sm:grid-cols-3 gap-8"><div><h3 className="text-sm uppercase tracking-wider text-white font-medium mb-4">了解我</h3><div className="text-xs space-y-2"><a className="block" href="#about">关于我</a><a className="block" href="#capabilities">核心能力</a><span className="block">职业经历</span></div></div><div><h3 className="text-sm uppercase tracking-wider text-white font-medium mb-4">观点内容</h3><div className="text-xs space-y-2"><span className="block">AI前沿观察</span><span className="block">产品拆解</span><span className="block">精选文章</span></div></div><div id="wechat"><h3 className="text-sm uppercase tracking-wider text-white font-medium mb-4">联系合作</h3><div className="text-xs space-y-2"><span className="block">微信：待补充</span><span className="block">邮箱：待补充</span><span className="block">求职 / 顾问 / 产品交流</span></div></div></div></div><div className="pt-6 border-t border-white/10 flex flex-col md:flex-row items-center justify-between gap-6 md:gap-4"><p className="text-[10px] uppercase tracking-widest opacity-50">Curated by 陈思东</p><div className="flex items-center gap-4"><span className="text-[10px] uppercase tracking-widest opacity-50">Join the Journey:</span><div className="flex gap-4">{socials.map(([label,Icon])=><a key={label} href="#contact" aria-label={label} className="opacity-70 hover:opacity-100"><Icon size={16}/></a>)}</div></div></div></motion.footer><div className="h-8"/></div>
  </div>
</main>}
